CREATE TABLE users
(
    ID       BIGINT PRIMARY KEY NOT NULL,
    LOGIN    VARCHAR UNIQUE     NOT NULL,
    PASSWORD VARCHAR            NOT NULL
);

CREATE TABLE roles
(
    ID   BIGINT PRIMARY KEY NOT NULL,
    NAME VARCHAR            NOT NULL
);

CREATE TABLE users_roles
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

ALTER TABLE users_roles
    ADD FOREIGN KEY (USER_ID)
        REFERENCES users (ID)
        ON DELETE CASCADE;

ALTER TABLE users_roles
    ADD FOREIGN KEY (ROLE_ID)
        REFERENCES roles (ID)
        ON DELETE CASCADE;

INSERT INTO roles (ID, NAME)
VALUES (1, 'ROLE_ADMIN'),
       (2, 'ROLE_USER');

INSERT INTO users (ID, LOGIN, PASSWORD)
VALUES (1, 'ADMIN', '$2a$12$LL4D0Xmeitq40DbINWApdeDH6ljxCIPfVz4Yxi2e0ZrPTUFSZmSNy');

INSERT INTO users_roles (USER_ID, ROLE_ID)
VALUES (1, 1);